import { useState, useEffect } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { db } from "../database.config";

const Home: NextPage = () => {
  const router = useRouter();
  const [message, setMessage] = useState("");

  const loginUser = async (e: React.FormEvent<HTMLFormElement>) => {
    try {
      e.preventDefault();
      const formData = new FormData(e.currentTarget);
      const data = Object.fromEntries(formData.entries());

      const user = await db.users
        .where("email")
        .equals(data.email.toString())
        .first();
      if (user) {
        if (user.password === data.password.toString()) {
          e.currentTarget.reset();
          console.log("User logged in with id: ", user.id);
          alert("Usuario logeado con el id: " + user.id);
          router.push("/welcome");
        } else {
          setMessage("Contraseña incorrecta");
        }
      } else {
        setMessage("Usuario no encontrado");
      }
    } catch (error) {
      console.log(error);
      setMessage("Error al logear el usuario");
    }
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      setMessage("");
    }, 3000);
    return () => clearTimeout(timer);
  }, [message]);

  return (
    <div>
      <Head>
        <title>Hack Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="w-screen h-screen flex justify-center items-center
    bg-gradient-to-br from-purple-700 to-amber-700"
      >
        <form
          action="POST"
          onSubmit={loginUser}
          className="p-10 bg-white rounded-xl drop-shadow-lg space-y-5"
        >
          <h1 className="text-center text-3xl">The Safest.net</h1>

          {message && message !== "" && (
            <div
              className="flex p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800"
              role="alert"
            >
              <svg
                aria-hidden="true"
                className="flex-shrink-0 inline w-5 h-5 mr-3"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                  clip-rule="evenodd"
                ></path>
              </svg>
              <span className="sr-only">Info</span>
              <div>{message}.</div>
            </div>
          )}

          <div className="flex flex-col space-y-2">
            <label className="text-sm font-light" htmlFor="email">
              Email
            </label>
            <input
              required
              className="w-96 px-3 py-2 rounded-md border border-slate-400"
              type="email"
              placeholder="Your Email"
              name="email"
              id="email"
            />
          </div>
          <div className="flex flex-col space-y-2">
            <label className="text-sm font-light" htmlFor="password">
              Contraseña
            </label>
            <input
              required
              className="w-96 px-3 py-2 rounded-md border border-slate-400"
              type="password"
              placeholder="Your Password"
              name="password"
              id="password"
            />
          </div>

          <div className="flex items-center gap-2">
            <input type="checkbox" name="remember" id="remember" />
            <label className="text-sm font-light" htmlFor="remember">
              Recordar
            </label>
          </div>

          <button
            className="w-full px-10 py-2 bg-blue-600 text-white rounded-md
            hover:bg-blue-500 hover:drop-shadow-md duration-300 ease-in"
            type="submit"
          >
            Ingresar
          </button>

          <p className="text-right">
            <Link href="/create-user">
              <a
                className="text-blue-600 text-sm font-light hover:underline"
                href="https://www.kindacode.com"
              >
                Olvido la contraseña?
              </a>
            </Link>
          </p>
        </form>
      </div>
    </div>
  );
};

export default Home;
