import { useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Home: NextPage = () => {
  const [isRickRolled, setIsRickRolled] = useState(false);

  return (
    <div>
      <Head>
        <title>You Hacked Me!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="w-screen h-screen flex flex-col justify-center items-center
    bg-gradient-to-br from-purple-700 to-amber-700"
      >
        <div className="w-50 h-50">
          <h1 className="text-center text-3xl">You Hacked Me!!! 💀</h1>
          {isRickRolled ? (
            <iframe
              width="700"
              height="380"
              src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
              title="YouTube video player"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            ></iframe>
          ) : (
            <Image
              src="/img/hacked.gif"
              alt="hacked"
              width="700"
              height="380"
            />
          )}
        </div>
        <div className="flex justify-center items-center gap-2 pt-6 ">
          <button
            className="w-100 px-10 py-2 bg-blue-600 text-white rounded-md"
            onClick={() => setIsRickRolled(!isRickRolled)}
          >
            Click Me
          </button>
          <button className="w-100 px-10 py-2 bg-blue-600 text-white rounded-md">
            <Link href="/create-user">
              <a>Crear Usuario</a>
            </Link>
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
